[build]
  command = "npm install && npm run build"
  publish = "dist/movieapp" # Ajusta si tu carpeta 'dist' es diferente (e.g., dist/movieapp)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200